#pragma once

#define SE3D_TAB          VK_TAB
#define SE3D_ENTER        VK_RETURN
#define SE3D_LEFTSHIFT    VK_LSHIFT
#define SE3D_RIGHTSHIFT   VK_RSHIFT
#define SE3D_LEFTCONTROL  VK_LCONTROL
#define SE3D_RIGHTCONTROL VK_RCONTROL
#define SE3D_ALT          VK_MENU
#define SE3D_CAPSLOCK     VK_CAPITAL
#define SE3D_ESCAPE       VK_ESCAPE
#define SE3D_PAGEUP       VK_PRIOR
#define SE3D_PAGEDOWN     VK_NEXT
#define SE3D_END          VK_END
#define SE3D_HOME         VK_HOME
#define SE3D_LEFT         VK_LEFT
#define SE3D_UP           VK_UP
#define SE3D_RIGHT        VK_RIGHT
#define SE3D_DOWN         VK_DOWN
#define SE3D_PRINT        VK_PRINT
#define SE3D_INSERT       VK_INSERT
#define SE3D_DELETE       VK_DELETE
#define SE3D_LEFTWIN      VK_LWIN
#define SE3D_RIGHTWIN     VK_RWIN
#define SE3D_NUM0         VK_NUMPAD0
#define SE3D_NUM1         VK_NUMPAD1
#define SE3D_NUM2         VK_NUMPAD2
#define SE3D_NUM3         VK_NUMPAD3
#define SE3D_NUM4         VK_NUMPAD4
#define SE3D_NUM5         VK_NUMPAD5
#define SE3D_NUM6         VK_NUMPAD6
#define SE3D_NUM7         VK_NUMPAD7
#define SE3D_NUM8         VK_NUMPAD8
#define SE3D_NUM9         VK_NUMPAD9
#define SE3D_MULTIPLY     VK_MULTIPLY
#define SE3D_SEPARATOR    VK_SEPARATOR
#define SE3D_MULTIPLY     VK_MULTIPLY
#define SE3D_SUBTRACT     VK_SUBTRACT
#define SE3D_DECIMAL      VK_DECIMAL
#define SE3D_DIVIDE       VK_DIVIDE
#define SE3D_F1           VK_F1
#define SE3D_F2           VK_F2
#define SE3D_F3           VK_F3
#define SE3D_F4           VK_F4
#define SE3D_F5           VK_F5
#define SE3D_F6           VK_F6
#define SE3D_F7           VK_F7
#define SE3D_F8           VK_F8
#define SE3D_F9           VK_F9
#define SE3D_F10          VK_F10
#define SE3D_F11          VK_F11
#define SE3D_F12          VK_F12
#define SE3D_VOLUMEMUTE   VK_VOLUME_MUTE
#define SE3D_VOLUMEDOWN   VK_VOLUME_DOWN
#define SE3D_VOLUMEUP     VK_VOLUME_UP
